### ISSUE TITLE
Experiment Problem

### ISSUE THREAD

**Issue by yufeng9819** [junshengzhou/3DAttriFlow#11]
Hi! Sorry to disturb you again.

I am following your wonderful work. But I got into trouble about reproduce the results of the PSGN(Fan et al. 2017) since I can not get the checkpoint of their experiment.  I want to know how to reproduce their results in your work.

Thank you for your help!

**Comment by junshengzhou** [comment]
Hi,
We follow the details in their paper and codes to reproduce their results. Also, you can refer to the pytorch implemented model files provided by OccNet [here](https://github.com/autonomousvision/occupancy_networks/tree/master/im2mesh/psgn/models).
And if you find our work useful, please consider staring our repo.

**Comment by yufeng9819** [comment]
Ok, thanks a lot!
