### ISSUE TITLE
Do you have faces for 2048.xyz? Or it just have no faces information

### ISSUE THREAD

**Issue by sumai-1998** [junshengzhou/3DAttriFlow#3]

**Comment by junshengzhou** [comment]
Hi,

We don't have the face information since we only focus on the point cloud processing. If you need a corresponding mesh, I‘d suggest to first correct a ball mesh and sample 2048 points on it uniformly using open3d.

**Comment by sumai-1998** [comment]
> 

Thanks for your reply,
 Actually i already done this， i obtain a mesh with o3d.geometry.TriangleMesh.create_from_point_cloud_XXXX(all 3 meshtods), and get a water tight mesh from 2048.xyz, it seems okay when the point cloud is a ball, but when i apply this faces information to the output of the 3DAttriflow, such as airplane or bench, the mesh is fully of  sharp corners, i have shown this in [my repo](https://github.com/sumai-1998/Github_problems/blob/main/3DAF_problems/ball_and_airplane.jpeg), and the raw file also [here](https://github.com/sumai-1998/Github_problems/tree/main/3DAF_problems).  I wonder if this might be caused by the incorrect information of faces generated by o3d randomly? Or others?

**Comment by junshengzhou** [comment]
Hi,

It's a big challenge to extract faces directly from point clouds, so it's normal that o3d failed to reconstruct complex shapes. There are a lot of works trying to reconstruct surfaces from point clouds, but we don't focus on that since 3DAttri is designed for the task of point cloud generation.

**Comment by sumai-1998** [comment]
> Hi,
> 
> It's a big challenge to extract faces directly from point clouds, so it's normal that o3d failed to reconstruct complex shapes. There are a lot of works trying to reconstruct surfaces from point clouds, but we don't focus on that since 3DAttri is designed for the task of point cloud generation.

okay, thanks a lot
