### ISSUE TITLE
Question about environment

### ISSUE THREAD

**Issue by yufeng9819** [junshengzhou/3DAttriFlow#5]
<img width="800" alt="截屏2022-09-25 15 50 24" src="https://user-images.githubusercontent.com/113972543/192133674-67afad35-f2f3-4618-bfa6-e587e1a7379a.png">

Hi! Thank you for your wonderful work. Now, I follow your guidance in README to prepare my environment(pip install requirement.txt). But I meet a problem. As image show above, the warring "AttributeError: 'Munch' object has no attribute 'demo'" occurs when I run python val_svr.py. So have you ever meet this problem before? Thanks for your response.

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest. I didn't meet the problem before. But I think the problem is caused by the config loading, since 'opt.demo' is from the config. I suggest you to have a check on the config file.

**Comment by yufeng9819** [comment]
Thanks for your response! I have solved my problem. It may caused by my environment setting when try to debug your code. Then I use python script to run "var_svr.py" and I did not meet this problem anymore.
