### ISSUE TITLE
Question about DP training

### ISSUE THREAD

**Issue by skyqwe123** [junshengzhou/3DAttriFlow#8]
python train_svr.py  -c cfgs/SVR.yaml -gpu 6,7 
Errors: 
train_svr.py", line 140, 
   net_loss_all.backward(torch.squeeze(torch.ones(torch.cuda.device_count())).cuda())
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([2]) and output[0] has a shape of torch.Size([]).

**Comment by junshengzhou** [comment]
Hi,
I didn't meet that problem. I notice that you use two gpus, maybe you can try to use a single gpu.

**Comment by skyqwe123** [comment]
@junshengzhou  Thanks for your reply.
I have another question.
The performance indicators reported in Table 1 are slightly different from those reported in the references. Are these indicators copied or reproduced by yourself?
for example，in table 1.

...                    Average (10^2)
AtlasNet [5]     3.59
OccNet [26]     4.15
3DAttriFlow     3.02
(Ours)

but in OccNet [26],  it's  mean Chamfer-L1 is 0.215
Did I neglect some details, such as sampling points?

**Comment by junshengzhou** [comment]
Hi,
The evaluation settings (e.g. point numbers, shape scales) in calculating metrics is quite different in different works(e.g. OccNet, Atlasnet, PSGN). For a fair comparison, we use their provided models to test their performance in the same evaluation setting.
