### ISSUE TITLE
Question about train and test strategy

### ISSUE THREAD

**Issue by yufeng9819** [junshengzhou/3DAttriFlow#9]
Hey! Sorry to disturb you again.

I want to ask  questions about train and test strategy. I find that in SVR.yaml file, you choose to set only one class to train and test, which means that 13 categories of training and testing are conducted separately. In OccNet experiment setting, they choose to set shapenet13==True and it means that they choose all categories. Therefore, both of your experiment setting are different and I want to know how get these results in table 1 metric by L1 Chamfer Distance. Another question is that why the results in OccNet table 1 metric by L1-Charmfer and your paper table 1 metric by L1 Chamfer Distance are quite different.

Looking forward to your reply! Thanks.

**Comment by junshengzhou** [comment]
Hi,
We train on all the 13 categories by setting `shapenet13: True`, the `class_choice` is only for debugging.
The evaluation settings (e.g. point numbers) in calculating metrics is quite different in different works(e.g. OccNet, Atlasnet, PSGN). For a fair comparison, we use their provided models to test their performance in the same evaluation setting.
